name: Deploy to Server

on:
  push:
    branches:
      - main   # or master, depends on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "cd ${{ secrets.SERVER_PATH }} && git pull origin main && npm install && npm run build"

      - name: Notify deployment status
        run: echo "✅ Deployment and build completed successfully!"